name:                multioptimizer
version:             0.1.0.0
github:              "githubuser/multioptimizer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/multioptimizer#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- vector-algorithms
- operational
- list-t
- transformers
- mtl
- containers
- random-source
- random-fu # many deps for this one
- clock
- safe
- errors

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -O2

executables:
  example-tsp:
    main: Main.hs
    source-dirs: examples/tsp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - multioptimizer

tests:
  multioptimizer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multioptimizer
    - tasty
    - tasty-hunit
    - pretty-simple
